/*
 * Citation
 * 1) Scope: Module frontend/src/routes/index.tsx
 * 2) Date: 2026-03-02
 * 3) Originality: Adapted from project route conventions; AI-assisted implementation of the home route and reset trigger UI.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

import { Title } from "@solidjs/meta";

export default function Home() {
  const handleReset = async () => {
    await fetch("/api/reset", { method: "POST" });
  };

  return (
    <main class="home-page">
      <Title>Home</Title>

      <h1>Home</h1>

      <button onClick={handleReset}>Reset Database</button>
    </main>
  );
}