/* Generated by AI then modified by me. */

import { createResource, For, Suspense } from 'solid-js';

type DbFetchTableProps = {
  table: string;
};

const DbFetchTable = (props: DbFetchTableProps) => {
  const [data] = createResource(() => props.table, async (table) => {
    const response = await fetch(`http://localhost:3000/api/${table}`);
    if (!response.ok) {
      throw new Error(`Failed to fetch table data: ${response.statusText}`);
    }
    return response.json();
  });

  return (
    <div class="table-container">
      <Suspense fallback={<p>Loading data...</p>}>
        {data() && data()?.length > 0 ? (
          <table class="db-table">
            <thead>
              <tr>
                <For each={Object.keys(data()[0])}>
                  {(key) => <th>{key}</th>}
                </For>
              </tr>
            </thead>
            <tbody>
              <For each={data()}>
                {(row) => (
                  <tr>
                    <For each={Object.values(row)}>
                      {(value) => <td>{String(value)}</td>}
                    </For>
                  </tr>
                )}
              </For>
            </tbody>
          </table>
        ) : (
          <p>No data available</p>
        )}
      </Suspense>
    </div>
  );
}

export default DbFetchTable;