/*
 * Citation
 * 1) Scope: Module frontend/src/components/DbFetchTable.tsx
 * 2) Date: 2026-03-16
 * 3) Originality: Adapted from existing project component; refactored to delegate formatting and API concerns to utility modules.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

import { createResource, For, Suspense, createSignal, Setter, createEffect, createMemo, onCleanup, onMount } from 'solid-js';
import { Portal } from 'solid-js/web';
import { getPrimaryKeys, getForeignKeys, ForeignKeyMetadata, isNullable, isAutoIncrement, getColumnDataType } from '~/utils/tableMetadata';
import {
  DataType,
  RelatedRowsByTable,
  castValue,
  detectType,
  findReferencedRow,
  formatColumnHeader,
  formatDateForDisplay,
  formatDateTimeForDisplay,
  getRowDisplayColumns,
  toComparableKey,
  toDateInputValue,
  toDateTimePickerValue,
} from '~/utils/dbTableFormatting';
import { createTableRow, deleteTableRow, fetchTableRows, updateTableRow } from '~/utils/dbTableApi';
import "./DbFetchTable.css";
import 'flatpickr/dist/flatpickr.min.css';


type DbFetchTableProps = {
  table: string;
};

const FK_MAX_RELATIONSHIP_DEPTH = 3;
type RelatedColumnsByTable = Record<string, string[]>;

type TemporalPickerProps = {
  value: any;
  dataType: 'date' | 'datetime';
  disabled: boolean;
  onInput: (value: string) => void;
};

const TemporalPicker = (props: TemporalPickerProps) => {
  let inputRef: HTMLInputElement | undefined;
  let pickerInstance: any;

  const getDateFormat = () => (props.dataType === 'date' ? 'Y-m-d' : 'Y-m-d H:i:S');
  const getAltFormat = () => (props.dataType === 'date' ? 'M j, Y' : 'M j, Y h:i K');
  const getNormalizedValue = () =>
    props.dataType === 'date' ? toDateInputValue(props.value) : toDateTimePickerValue(props.value);

  onMount(async () => {
    if (!inputRef) {
      return;
    }

    const normalizedValue = getNormalizedValue();
    if (normalizedValue) {
      inputRef.value = normalizedValue;
    }

    const flatpickrModule = await import('flatpickr');
    const flatpickr = flatpickrModule.default;

    pickerInstance = flatpickr(inputRef, {
      enableTime: props.dataType === 'datetime',
      enableSeconds: props.dataType === 'datetime',
      noCalendar: false,
      dateFormat: getDateFormat(),
      altInput: true,
      altFormat: getAltFormat(),
      allowInput: true,
      clickOpens: !props.disabled,
      defaultDate: normalizedValue || undefined,
      onChange: (_selectedDates: Date[], dateStr: string) => {
        props.onInput(dateStr);
      },
      onClose: (_selectedDates: Date[], dateStr: string) => {
        props.onInput(dateStr);
      },
    });
  });

  createEffect(() => {
    const normalizedValue = getNormalizedValue();

    if (pickerInstance) {
      pickerInstance.set('clickOpens', !props.disabled);
      pickerInstance.input.disabled = props.disabled;
      pickerInstance.altInput.disabled = props.disabled;
      pickerInstance.setDate(normalizedValue || '', false, getDateFormat());
      return;
    }

    if (inputRef) {
      inputRef.value = normalizedValue;
      inputRef.disabled = props.disabled;
    }
  });

  onCleanup(() => {
    if (pickerInstance) {
      pickerInstance.destroy();
    }
  });

  return <input ref={inputRef} type="text" />;
};


type EmbeddedRowPreviewProps = {
  table: string;
  row: Record<string, any>;
  relatedRows: RelatedRowsByTable;
  relatedColumns: RelatedColumnsByTable;
  depth: number;
};

const EmbeddedRowPreview = (props: EmbeddedRowPreviewProps) => {
  const columns = createMemo(() => getRowDisplayColumns(props.row, props.relatedColumns[props.table]));
  const foreignKeyMap = createMemo(() => {
    const map: Record<string, ForeignKeyMetadata> = {};
    getForeignKeys(props.table).forEach((foreignKey) => {
      map[foreignKey.column] = foreignKey;
    });
    return map;
  });

  return (
    <div class="fk-embed-container">
      <table class="fk-embed-table">
        <tbody>
          <tr class="fk-embed-header-row">
            <For each={columns()}>
              {(column) => <td>{formatColumnHeader(column)}</td>}
            </For>
          </tr>
          <tr>
            <For each={columns()}>
              {(column) => {
                const foreignKey = foreignKeyMap()[column];
                const value = props.row[column];

                if (!foreignKey || props.depth >= FK_MAX_RELATIONSHIP_DEPTH) {
                  return <td>{String(value)}</td>;
                }

                const referencedRow = findReferencedRow(foreignKey, value, props.relatedRows);

                if (!referencedRow) {
                  return <td>{String(value)}</td>;
                }

                return (
                  <td>
                    <EmbeddedRowPreview
                      table={foreignKey.referencesTable}
                      row={referencedRow}
                      relatedRows={props.relatedRows}
                      relatedColumns={props.relatedColumns}
                      depth={props.depth + 1}
                    />
                  </td>
                );
              }}
            </For>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

type ForeignKeyPickerProps = {
  foreignKey: ForeignKeyMetadata;
  value: any;
  rows: Record<string, any>[];
  columns: string[];
  relatedRows: RelatedRowsByTable;
  relatedColumns: RelatedColumnsByTable;
  disabled: boolean;
  onConfirm: (value: any) => void;
};

const ForeignKeyPicker = (props: ForeignKeyPickerProps) => {
  const [open, setOpen] = createSignal(false);
  const [dropdownStyle, setDropdownStyle] = createSignal<Record<string, string>>({});
  let buttonRef: HTMLButtonElement | undefined;
  let dropdownRef: HTMLDivElement | undefined;

  const selectedRow = createMemo(() => {
    const valueKey = toComparableKey(props.value);
    if (!valueKey) {
      return undefined;
    }
    return props.rows.find((row) => toComparableKey(row[props.foreignKey.referencesColumn]) === valueKey);
  });

  const handleRowClick = (row: Record<string, any>) => {
    props.onConfirm(row[props.foreignKey.referencesColumn]);
    setOpen(false);
  };

  const updateDropdownPosition = () => {
    if (!buttonRef) {
      return;
    }

    const rect = buttonRef.getBoundingClientRect();
    const viewportPadding = 12;
    const dropdownGap = 4;
    const estimatedDropdownHeight = 260;

    const availableBelow = window.innerHeight - rect.bottom - viewportPadding;
    const availableAbove = rect.top - viewportPadding;
    const shouldOpenAbove = availableBelow < estimatedDropdownHeight && availableAbove > availableBelow;

    const left = Math.max(viewportPadding, rect.left);
    const maxWidth = Math.max(240, window.innerWidth - left - viewportPadding);
    const top = shouldOpenAbove ? rect.top - dropdownGap : rect.bottom + dropdownGap;

    setDropdownStyle({
      position: 'fixed',
      top: `${top}px`,
      left: `${left}px`,
      transform: shouldOpenAbove ? 'translateY(-100%)' : 'none',
      'min-width': `${rect.width}px`,
      'max-width': `${maxWidth}px`,
      'z-index': '5000',
    });
  };

  createEffect(() => {
    if (!open()) {
      return;
    }

    updateDropdownPosition();

    const handleWindowChange = () => updateDropdownPosition();
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Node | null;
      if (!target) {
        return;
      }

      const isInButton = !!buttonRef?.contains(target);
      const isInDropdown = !!dropdownRef?.contains(target);
      if (!isInButton && !isInDropdown) {
        setOpen(false);
      }
    };
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpen(false);
      }
    };

    window.addEventListener('resize', handleWindowChange);
    window.addEventListener('scroll', handleWindowChange, true);
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleEscape);

    onCleanup(() => {
      window.removeEventListener('resize', handleWindowChange);
      window.removeEventListener('scroll', handleWindowChange, true);
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    });
  });

  return (
    <div class="fk-picker">
      <button
        ref={buttonRef}
        type="button"
        class="fk-picker-button"
        onClick={() => setOpen((current) => !current)}
        disabled={props.disabled}
      >
        <span class="fk-picker-button-value">
          {selectedRow() ? (
            <EmbeddedRowPreview
              table={props.foreignKey.referencesTable}
              row={selectedRow()!}
              relatedRows={props.relatedRows}
              relatedColumns={props.relatedColumns}
              depth={0}
            />
          ) : (
            <span class="fk-picker-placeholder">Select {props.foreignKey.referencesTable}</span>
          )}
        </span>
        <span classList={{ 'fk-picker-arrow': true, 'fk-picker-arrow-open': open() }}>▾</span>
      </button>
      {open() && (
        <Portal>
          <div ref={dropdownRef} class="fk-picker-dropdown fk-picker-dropdown-portal" style={dropdownStyle()}>
            <div class="fk-picker-scroll">
              <table class="fk-picker-table">
                <thead>
                  <tr>
                    <For each={props.columns}>
                      {(column) => <th>{formatColumnHeader(column)}</th>}
                    </For>
                  </tr>
                </thead>
                <tbody>
                  <For each={props.rows}>
                    {(row) => {
                      const selectedValue = selectedRow()
                        ? toComparableKey(selectedRow()![props.foreignKey.referencesColumn])
                        : '';
                      const currentValue = toComparableKey(row[props.foreignKey.referencesColumn]);
                      return (
                        <tr
                          classList={{ 'fk-picker-selected': selectedValue === currentValue }}
                          onClick={() => handleRowClick(row)}
                        >
                          <For each={getRowDisplayColumns(row, props.columns)}>
                            {(column) => <td>{String(row[column])}</td>}
                          </For>
                        </tr>
                      );
                    }}
                  </For>
                </tbody>
              </table>
            </div>
          </div>
        </Portal>
      )}
    </div>
  );
};

type DataRowProps = {
  rowIndex: number;
  row: Record<string, any>;
  columns: string[];
  columnTypes: Record<string, DataType>;
  primaryKeys: string[];
  table: string;
  foreignKeyMap: Record<string, ForeignKeyMetadata>;
  relatedRows: RelatedRowsByTable;
  relatedColumns: RelatedColumnsByTable;
  editingId: number | null;
  setEditingId: Setter<number | null>;
  onDelete: (index: number) => Promise<void>;
  onUpdate: (index: number, data: Record<string, any>) => Promise<void>;
};

const DataRow = (props: DataRowProps) => {
  const [editData, setEditData] = createSignal<Record<string, any>>({});
  const [error, setError] = createSignal<string>('');
  const [loading, setLoading] = createSignal<boolean>(false);
  const isEditing = createMemo(() => props.editingId === props.rowIndex);

  const handleEditClick = () => {
    if (isEditing()) {
      props.setEditingId(null);
    } else {
      const data: Record<string, any> = {};
      props.columns.forEach(col => {
        data[col] = props.row[col];
      });
      setEditData(data);
      props.setEditingId(props.rowIndex);
    }
  };

  const handleInputChange = (column: string, value: string) => {
    setEditData(prev => ({ ...prev, [column]: value }));
  };

  const handleDelete = async () => {
    setLoading(true);
    setError('');
    try {
      await props.onDelete(props.rowIndex);
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async () => {
    setLoading(true);
    setError('');
    try {
      const castData: Record<string, any> = {};
      props.columns.forEach(col => {
        const rawValue = editData()[col];
        const normalizedValue = rawValue === null || rawValue === undefined ? '' : String(rawValue);
        castData[col] = castValue(normalizedValue, props.columnTypes[col]);
      });
      await props.onUpdate(props.rowIndex, castData);
      props.setEditingId(null);
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  };

  const renderDisplayValue = (column: string) => {
    const foreignKey = props.foreignKeyMap[column];
    const value = props.row[column];

    if (!foreignKey) {
      if (props.columnTypes[column] === 'date') {
        return formatDateForDisplay(value);
      }
      if (props.columnTypes[column] === 'datetime') {
        return formatDateTimeForDisplay(value);
      }
      return String(value);
    }

    const referencedRow = findReferencedRow(foreignKey, value, props.relatedRows);

    if (!referencedRow) {
      return String(value);
    }

    return (
      <EmbeddedRowPreview
        table={foreignKey.referencesTable}
        row={referencedRow}
        relatedRows={props.relatedRows}
        relatedColumns={props.relatedColumns}
        depth={0}
      />
    );
  };

  return (
    <>
      <tr>
        <For each={props.columns}>
          {(column) => (
            <td classList={{ 'fk-cell': !isEditing() && Boolean(props.foreignKeyMap[column]) }}>
              {isEditing() ? (
                props.foreignKeyMap[column] ? (
                  <ForeignKeyPicker
                    foreignKey={props.foreignKeyMap[column]}
                    value={editData()[column]}
                    rows={props.relatedRows[props.foreignKeyMap[column].referencesTable] || []}
                    columns={props.relatedColumns[props.foreignKeyMap[column].referencesTable] || []}
                    relatedRows={props.relatedRows}
                    relatedColumns={props.relatedColumns}
                    disabled={loading()}
                    onConfirm={(value) => setEditData((prev) => ({ ...prev, [column]: value }))}
                  />
                ) : (
                  props.columnTypes[column] === 'date' ? (
                    <TemporalPicker
                      value={editData()[column]}
                      dataType="date"
                      disabled={loading()}
                      onInput={(value) => handleInputChange(column, value)}
                    />
                  ) : props.columnTypes[column] === 'datetime' ? (
                    <TemporalPicker
                      value={editData()[column]}
                      dataType="datetime"
                      disabled={loading()}
                      onInput={(value) => handleInputChange(column, value)}
                    />
                  ) : (
                    <input
                      type="text"
                      value={editData()[column] ?? ''}
                      onInput={(e) => handleInputChange(column, e.currentTarget.value)}
                      disabled={loading()}
                    />
                  )
                )
              ) : (
                renderDisplayValue(column)
              )}
            </td>
          )}
        </For>
        <td class="trash">
          <button onClick={handleDelete} disabled={loading()}>🗑️</button>
          {isEditing() ? (
            <button onClick={handleSubmit} disabled={loading()}>✓</button>
          ) : (
            <button onClick={handleEditClick} disabled={loading()}>✏️</button>
          )}
        </td>
      </tr>
      {error() && (
        <tr>
          <td colSpan={props.columns.length + 1} style={{ color: 'red', padding: '10px' }}>
            Error: {error()}
          </td>
        </tr>
      )}
    </>
  );
};

type FormRowProps = {
  columns: string[];
  columnTypes: Record<string, DataType>;
  foreignKeyMap: Record<string, ForeignKeyMetadata>;
  relatedRows: RelatedRowsByTable;
  relatedColumns: RelatedColumnsByTable;
  table: string;
  onAddRow: (row: Record<string, any>) => Promise<void>;
};

const FormRow = (props: FormRowProps) => {
  const [formData, setFormData] = createSignal<Record<string, string>>({});
  const [error, setError] = createSignal<string>('');
  const [loading, setLoading] = createSignal<boolean>(false);

  const handleInputChange = (column: string, value: string) => {
    setFormData(prev => ({ ...prev, [column]: value }));
  };

  const handleSubmit = async () => {
    setLoading(true);
    setError('');
    try {
      const castData: Record<string, any> = {};
      props.columns.forEach(col => {
        const rawValue = formData()[col];
        const normalizedValue = rawValue === null || rawValue === undefined ? '' : String(rawValue);

        // Skip auto-increment fields if empty (let DB generate)
        if (isAutoIncrement(props.table, col) && normalizedValue === '') {
          return;
        }

        // Convert empty nullable fields to NULL
        if (isNullable(props.table, col) && normalizedValue === '') {
          castData[col] = null;
          return;
        }

        // Default NOT NULL string fields to empty string
        if (normalizedValue === '' && props.columnTypes[col] === 'string') {
          castData[col] = '';
          return;
        }

        castData[col] = castValue(normalizedValue, props.columnTypes[col]);
      });
      await props.onAddRow(castData);
      setFormData({});
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <tr class="form-row">
        <For each={props.columns}>
          {(column) => (
            <td>
              {props.foreignKeyMap[column] ? (
                <ForeignKeyPicker
                  foreignKey={props.foreignKeyMap[column]}
                  value={formData()[column]}
                  rows={props.relatedRows[props.foreignKeyMap[column].referencesTable] || []}
                  columns={props.relatedColumns[props.foreignKeyMap[column].referencesTable] || []}
                  relatedRows={props.relatedRows}
                  relatedColumns={props.relatedColumns}
                  disabled={loading()}
                  onConfirm={(value) => handleInputChange(column, String(value))}
                />
              ) : (
                props.columnTypes[column] === 'date' ? (
                  <TemporalPicker
                    value={formData()[column] || ''}
                    dataType="date"
                    disabled={loading()}
                    onInput={(value) => handleInputChange(column, value)}
                  />
                ) : props.columnTypes[column] === 'datetime' ? (
                  <TemporalPicker
                    value={formData()[column] || ''}
                    dataType="datetime"
                    disabled={loading()}
                    onInput={(value) => handleInputChange(column, value)}
                  />
                ) : (
                  <input
                    type="text"
                    placeholder={
                      isAutoIncrement(props.table, column)
                        ? `${formatColumnHeader(column)} (auto)`
                        : isNullable(props.table, column)
                          ? `${formatColumnHeader(column)} (optional)`
                          : formatColumnHeader(column)
                    }
                    value={formData()[column] || ''}
                    onInput={(e) => handleInputChange(column, e.currentTarget.value)}
                    disabled={loading()}
                  />
                )
              )}
            </td>
          )}
        </For>
        <td class="trash">
          <button onClick={handleSubmit} disabled={loading()}>✓</button>
        </td>
      </tr>
      {error() && (
        <tr>
          <td colSpan={props.columns.length + 1} style={{ color: 'red', padding: '10px' }}>
            Error: {error()}
          </td>
        </tr>
      )}
    </>
  );
};

const DbFetchTable = (props: DbFetchTableProps) => {
  const [editingId, setEditingId] = createSignal<number | null>(null);
  const [tableData, setTableData] = createSignal<Record<string, any>[]>([]);
  const [columns, setColumns] = createSignal<string[]>([]);
  const [columnTypes, setColumnTypes] = createSignal<Record<string, DataType>>({});
  const [relatedRows, setRelatedRows] = createSignal<RelatedRowsByTable>({});
  const [relatedColumns, setRelatedColumns] = createSignal<RelatedColumnsByTable>({});
  const [refetchCount, setRefetchCount] = createSignal<number>(0);
  const primaryKeys = getPrimaryKeys(props.table);
  const foreignKeyMap = createMemo(() => {
    const map: Record<string, ForeignKeyMetadata> = {};
    getForeignKeys(props.table).forEach((foreignKey) => {
      map[foreignKey.column] = foreignKey;
    });
    return map;
  });
  const relatedTables = createMemo(() => {
    return Array.from(new Set(getForeignKeys(props.table).map((foreignKey) => foreignKey.referencesTable)));
  });

  const [data] = createResource(
    () => ({ table: props.table, refetch: refetchCount() }),
    async ({ table }) => {
      return fetchTableRows(table);
    }
  );

  const [relatedData] = createResource(
    () => ({ tables: relatedTables(), refetch: refetchCount() }),
    async ({ tables }) => {
      const entries = await Promise.all(
        tables.map(async (table) => {
          const rows = await fetchTableRows(table);
          return [table, rows as Record<string, any>[]] as const;
        })
      );

      return Object.fromEntries(entries) as RelatedRowsByTable;
    }
  );

  createEffect(() => {
    const rows = data() || [];
    setTableData([...rows]);

    if (rows.length > 0) {
      const cols = Object.keys(rows[0]);
      setColumns(cols);

      const types: Record<string, DataType> = {};
      cols.forEach(col => {
        types[col] = detectType(rows[0][col], col, getColumnDataType(props.table, col));
      });
      setColumnTypes(types);
    }
  });

  createEffect(() => {
    if (relatedData()) {
      setRelatedRows(relatedData()!);

      const columnsByTable: RelatedColumnsByTable = {};
      Object.entries(relatedData()!).forEach(([table, rows]) => {
        columnsByTable[table] = rows.length > 0 ? Object.keys(rows[0]) : [];
      });
      setRelatedColumns(columnsByTable);
    }
  });

  onMount(() => {
    const eventSource = new EventSource('/api/stream');

    const handleDbUpdate = (event: MessageEvent) => {
      try {
        const payload = JSON.parse(event.data) as { table?: string };
        if (payload.table === props.table || relatedTables().includes(payload.table || '') || payload.table === '*') {
          setRefetchCount((count) => count + 1);
        }
      } catch (error) {
        console.error('Failed to parse db-update event:', error);
      }
    };

    eventSource.addEventListener('db-update', handleDbUpdate);

    onCleanup(() => {
      eventSource.removeEventListener('db-update', handleDbUpdate);
      eventSource.close();
    });
  });

  const handleDeleteRow = async (index: number) => {
    const row = tableData()[index];
    const where: Record<string, any> = {};

    primaryKeys.forEach(pk => {
      where[pk] = row[pk];
    });

    try {
      await deleteTableRow(props.table, where);

      const currentEditingId = editingId();
      if (currentEditingId !== null) {
        if (currentEditingId === index) {
          setEditingId(null);
        } else if (currentEditingId > index) {
          setEditingId(currentEditingId - 1);
        }
      }

      setRefetchCount(c => c + 1);
    } catch (err) {
      throw err;
    }
  };

  const handleUpdateRow = async (index: number, newData: Record<string, any>) => {
    const oldRow = tableData()[index];
    const where: Record<string, any> = {};

    primaryKeys.forEach(pk => {
      where[pk] = oldRow[pk];
    });

    try {
      await updateTableRow(props.table, newData, where);
      setRefetchCount(c => c + 1);
    } catch (err) {
      throw err;
    }
  };

  const handleAddRow = async (newRow: Record<string, any>) => {
    try {
      await createTableRow(props.table, newRow);
      setRefetchCount(c => c + 1);
    } catch (err) {
      throw err;
    }
  };

  return (
    <div class="table-container">
      <Suspense fallback={<p>Loading data...</p>}>
        {columns().length > 0 ? (
          <table class="db-table">
            <thead>
              <tr>
                <For each={columns()}>
                  {(key) => <th>{formatColumnHeader(key)}</th>}
                </For>
              </tr>
            </thead>
            <tbody>
              <For each={tableData()}>
                {(row, index) => (
                  <DataRow
                    rowIndex={index()}
                    row={row}
                    columns={columns()}
                    columnTypes={columnTypes()}
                    primaryKeys={primaryKeys}
                    table={props.table}
                    foreignKeyMap={foreignKeyMap()}
                    relatedRows={relatedRows()}
                    relatedColumns={relatedColumns()}
                    editingId={editingId()}
                    setEditingId={setEditingId}
                    onDelete={handleDeleteRow}
                    onUpdate={handleUpdateRow}
                  />
                )}
              </For>
              <FormRow
                columns={columns()}
                columnTypes={columnTypes()}
                foreignKeyMap={foreignKeyMap()}
                relatedRows={relatedRows()}
                relatedColumns={relatedColumns()}
                table={props.table}
                onAddRow={handleAddRow}
              />
            </tbody>
          </table>
        ) : (
          <p>No data available</p>
        )}
      </Suspense>
    </div>
  );
}

export default DbFetchTable;