/*
 * Citation
 * 1) Scope: Module frontend/src/utils/dbTableApi.ts
 * 2) Date: 2026-03-16
 * 3) Originality: Adapted from existing project code in DbFetchTable.tsx; extracted API concerns into utility functions.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

export const getApiUrl = (table: string): string => {
  if (import.meta.env.SSR) {
    const port = import.meta.env.VITE_PORT || '3000';
    return `http://localhost:${port}/api/${table}`;
  }
  return `/api/${table}`;
};

const parseError = async (response: Response, fallbackMessage: string): Promise<Error> => {
  try {
    const payload = await response.json();
    return new Error(payload.error || fallbackMessage);
  } catch {
    return new Error(fallbackMessage);
  }
};

export const fetchTableRows = async (table: string): Promise<Record<string, any>[]> => {
  const response = await fetch(getApiUrl(table));
  if (!response.ok) {
    throw await parseError(response, `Failed to fetch table ${table}`);
  }
  return response.json();
};

export const deleteTableRow = async (table: string, where: Record<string, any>): Promise<void> => {
  const response = await fetch(getApiUrl(table), {
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ where }),
  });

  if (!response.ok) {
    throw await parseError(response, 'Failed to delete row');
  }
};

export const updateTableRow = async (
  table: string,
  data: Record<string, any>,
  where: Record<string, any>,
): Promise<void> => {
  const response = await fetch(getApiUrl(table), {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ data, where }),
  });

  if (!response.ok) {
    throw await parseError(response, 'Failed to update row');
  }
};

export const createTableRow = async (table: string, data: Record<string, any>): Promise<void> => {
  const response = await fetch(getApiUrl(table), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ data }),
  });

  if (!response.ok) {
    throw await parseError(response, 'Failed to create row');
  }
};
