/*
 * Citation
 * 1) Scope: Module frontend/src/utils/dbTableFormatting.ts
 * 2) Date: 2026-03-16
 * 3) Originality: Adapted from existing project code in DbFetchTable.tsx; refactored into reusable utilities.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

import { ForeignKeyMetadata } from './tableMetadata';

export type DataType = 'number' | 'boolean' | 'string' | 'date' | 'datetime';
export type RelatedRowsByTable = Record<string, Record<string, any>[]>;

const isDateLikeColumnName = (column: string): boolean => {
  return /(^|_)(date|dob|birth|birthday)(_|$)/i.test(column);
};

export const formatColumnHeader = (key: string): string => {
  return key
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

export const detectType = (value: any, column?: string, configuredType?: 'date' | 'datetime'): DataType => {
  if (configuredType) {
    return configuredType;
  }

  const hasDateColumnHint = !!column && isDateLikeColumnName(column);

  if (typeof value === 'number') return 'number';
  if (typeof value === 'boolean') return 'boolean';
  if (value instanceof Date) return hasDateColumnHint ? 'date' : 'datetime';
  if (typeof value === 'string') {
    if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return 'date';
    if (/^\d{4}-\d{2}-\d{2}T/.test(value) || /^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}/.test(value)) {
      if (hasDateColumnHint) return 'date';
      return 'datetime';
    }
    if (/^\d{4}-\d{2}-\d{2}/.test(value)) return 'date';
  }
  return 'string';
};

const toDateTimeLocalValue = (value: any): string => {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) {
    if (Number.isNaN(value.getTime())) return '';
    const year = value.getFullYear();
    const month = String(value.getMonth() + 1).padStart(2, '0');
    const day = String(value.getDate()).padStart(2, '0');
    const hours = String(value.getHours()).padStart(2, '0');
    const minutes = String(value.getMinutes()).padStart(2, '0');
    return `${year}-${month}-${day}T${hours}:${minutes}`;
  }

  const raw = String(value).trim();
  const exactMatch = raw.match(/^(\d{4}-\d{2}-\d{2})[T\s](\d{2}:\d{2})(?::\d{2}(?:\.\d+)?)?$/);
  if (exactMatch) {
    return `${exactMatch[1]}T${exactMatch[2]}`;
  }

  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return '';

  const year = parsed.getFullYear();
  const month = String(parsed.getMonth() + 1).padStart(2, '0');
  const day = String(parsed.getDate()).padStart(2, '0');
  const hours = String(parsed.getHours()).padStart(2, '0');
  const minutes = String(parsed.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

export const toDateInputValue = (value: any): string => {
  if (value === null || value === undefined) return '';
  const raw = String(value).trim();
  const match = raw.match(/^(\d{4}-\d{2}-\d{2})/);
  if (match) return match[1];

  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return '';

  const year = parsed.getUTCFullYear();
  const month = String(parsed.getUTCMonth() + 1).padStart(2, '0');
  const day = String(parsed.getUTCDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const formatDateForDisplay = (value: any): string => {
  const dateValue = toDateInputValue(value);
  if (!dateValue) {
    return value === null || value === undefined ? '' : String(value);
  }

  const [year, month, day] = dateValue.split('-').map(Number);
  const utcDate = new Date(Date.UTC(year, month - 1, day));
  return new Intl.DateTimeFormat(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  }).format(utcDate);
};

export const formatDateTimeForDisplay = (value: any): string => {
  const dateTimeValue = toDateTimeLocalValue(value);
  if (!dateTimeValue) {
    return value === null || value === undefined ? '' : String(value);
  }

  const parsed = new Date(dateTimeValue);
  if (Number.isNaN(parsed.getTime())) {
    return value === null || value === undefined ? '' : String(value);
  }

  return new Intl.DateTimeFormat(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(parsed);
};

export const toDateTimePickerValue = (value: any): string => {
  const localValue = toDateTimeLocalValue(value);
  if (!localValue) {
    return '';
  }
  return `${localValue.replace('T', ' ')}:00`;
};

export const castValue = (value: string, type: DataType): any => {
  if (!value && value !== '0') return null;

  switch (type) {
    case 'number': {
      const parsedNumber = parseFloat(value);
      return Number.isNaN(parsedNumber) ? value : parsedNumber;
    }
    case 'boolean':
      return value === '1' || value === 'true';
    case 'date':
      return toDateInputValue(value);
    case 'datetime':
      if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value)) {
        return `${value.replace('T', ' ')}:00`;
      }
      if (/^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}$/.test(value)) {
        return `${value}:00`;
      }
      return value;
    default:
      return value;
  }
};

export const toComparableKey = (value: any): string => {
  if (value === null || value === undefined) {
    return '';
  }
  return String(value);
};

export const getRowDisplayColumns = (row: Record<string, any>, explicitColumns?: string[]): string[] => {
  if (explicitColumns && explicitColumns.length > 0) {
    return explicitColumns;
  }
  return Object.keys(row);
};

export const findReferencedRow = (
  foreignKey: ForeignKeyMetadata,
  value: any,
  relatedRows: RelatedRowsByTable,
): Record<string, any> | undefined => {
  const rows = relatedRows[foreignKey.referencesTable] || [];
  const target = toComparableKey(value);
  return rows.find((row) => toComparableKey(row[foreignKey.referencesColumn]) === target);
};
