/*
 * Citation
 * 1) Scope: Module frontend/src/utils/realtime.ts
 * 2) Date: 2026-03-02
 * 3) Originality: Adapted to this project from standard pub/sub patterns; AI-assisted implementation for in-memory realtime event broadcasting.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

type DbUpdateEvent = {
  table: string;
  action: 'insert' | 'update' | 'delete' | 'reset';
  timestamp: number;
};

type RealtimeListener = (event: DbUpdateEvent) => void;

const listeners = new Set<RealtimeListener>();

export const subscribeToDbUpdates = (listener: RealtimeListener): (() => void) => {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
};

export const broadcastDbUpdate = (event: Omit<DbUpdateEvent, 'timestamp'>): void => {
  const payload: DbUpdateEvent = {
    ...event,
    timestamp: Date.now(),
  };

  listeners.forEach((listener) => {
    try {
      listener(payload);
    } catch (error) {
      console.error('Realtime listener error:', error);
    }
  });
};
