/*
 * Citation
 * 1) Scope: Module frontend/src/routes/api/[table].ts
 * 2) Date: 2026-03-16
 * 3) Originality: Based on the existing project API route; adapted to execute stored procedures for CRUD operations.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

import { json } from '@solidjs/router';
import { broadcastDbUpdate } from '~/utils/realtime';
import { pool } from '~/utils/dbPool';

const ALLOWED_TABLES = new Set([
  'Addresses',
  'People',
  'Roles',
  'Clubs',
  'Membership',
  'Events',
  'PhysicalEvents',
  'VirtualEvents',
]);

const validateTableName = (tableName: string): string | null => {
  if (!ALLOWED_TABLES.has(tableName)) {
    return `Unsupported table: ${tableName}`;
  }
  return null;
};

const normalizeProcedureRows = (raw: any): Record<string, any>[] => {
  if (!Array.isArray(raw)) {
    return [];
  }

  if (Array.isArray(raw[0])) {
    return raw[0] as Record<string, any>[];
  }

  return raw as Record<string, any>[];
};

export async function GET({ params }: { params: { table: string } }) {
  try {
    const tableName = params.table;
    const tableError = validateTableName(tableName);
    if (tableError) {
      return json({ error: tableError }, { status: 400 });
    }

    const [rows] = await pool.execute('CALL sp_select_table(?)', [tableName]);

    return json(normalizeProcedureRows(rows));
  } catch (error) {
    console.error('Database error:', error);
    return json({ error: 'Failed to fetch data' }, { status: 500 });
  }
}

export async function POST({ params, request }: { params: { table: string }; request: Request }) {
  try {
    const tableName = params.table;
    const tableError = validateTableName(tableName);
    if (tableError) {
      return json({ error: tableError }, { status: 400 });
    }

    const body = await request.json();
    const { data } = body;

    if (!data || typeof data !== 'object') {
      return json({ error: 'Invalid request body' }, { status: 400 });
    }

    await pool.execute('CALL sp_insert_row(?, ?)', [tableName, JSON.stringify(data)]);

    broadcastDbUpdate({ table: tableName, action: 'insert' });

    return json({ success: true, message: 'Row created successfully' });
  } catch (error) {
    console.error('Insert error:', error);
    return json({ error: String(error) }, { status: 500 });
  }
}

export async function PUT({ params, request }: { params: { table: string }; request: Request }) {
  try {
    const tableName = params.table;
    const tableError = validateTableName(tableName);
    if (tableError) {
      return json({ error: tableError }, { status: 400 });
    }

    const body = await request.json();
    const { data, where } = body;

    if (!data || !where) {
      return json({ error: 'Invalid request body' }, { status: 400 });
    }

    await pool.execute('CALL sp_update_row(?, ?, ?)', [tableName, JSON.stringify(data), JSON.stringify(where)]);

    broadcastDbUpdate({ table: tableName, action: 'update' });

    return json({ success: true, message: 'Row updated successfully' });
  } catch (error) {
    console.error('Update error:', error);
    return json({ error: String(error) }, { status: 500 });
  }
}

export async function DELETE({ params, request }: { params: { table: string }; request: Request }) {
  try {
    const tableName = params.table;
    const tableError = validateTableName(tableName);
    if (tableError) {
      return json({ error: tableError }, { status: 400 });
    }

    const body = await request.json();
    const { where } = body;

    if (!where) {
      return json({ error: 'Invalid request body' }, { status: 400 });
    }

    await pool.execute('CALL sp_delete_row(?, ?)', [tableName, JSON.stringify(where)]);

    broadcastDbUpdate({ table: tableName, action: 'delete' });

    return json({ success: true, message: 'Row deleted successfully' });
  } catch (error) {
    console.error('Delete error:', error);
    return json({ error: String(error) }, { status: 500 });
  }
}
