/*
 * Citation
 * 1) Scope: Module frontend/src/routes/api/reset.ts
 * 2) Date: 2026-03-02
 * 3) Originality: Based on existing project API patterns; AI-assisted route handler to call reset() and broadcast reset updates.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

import { json } from '@solidjs/router';
import { broadcastDbUpdate } from '~/utils/realtime';
import { pool } from '~/utils/dbPool';

export async function POST() {
  try {
    console.log('Calling reset() procedure');
    const connection = await pool.getConnection();
    
    await connection.query('CALL reset()');
    connection.release();

    broadcastDbUpdate({ table: '*', action: 'reset' });

    return json({ success: true, message: 'Database reset successfully' });
  } catch (error) {
    console.error('Reset error:', error);
    return json({ error: 'Failed to reset database' }, { status: 500 });
  }
}
