/*
 * Citation
 * 1) Scope: Module frontend/src/routes/api/stream.ts
 * 2) Date: 2026-03-02
 * 3) Originality: Based on project API route patterns; AI-assisted implementation of server-sent events streaming and keep-alive behavior.
 * 4) Source: https://github.com/features/copilot (Generated by GitHub Copilot, GPT-5.3-Codex)
 */

import { subscribeToDbUpdates } from '~/utils/realtime';

const encoder = new TextEncoder();

const encodeEvent = (event: string, payload: unknown): Uint8Array => {
  return encoder.encode(`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`);
};

export async function GET() {
  let cleanup: (() => void) | undefined;
  let keepAliveTimer: ReturnType<typeof setInterval> | undefined;

  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(encodeEvent('ready', { ok: true, timestamp: Date.now() }));

      cleanup = subscribeToDbUpdates((event) => {
        controller.enqueue(encodeEvent('db-update', event));
      });

      keepAliveTimer = setInterval(() => {
        controller.enqueue(encoder.encode(`: ping ${Date.now()}\n\n`));
      }, 25000);
    },
    cancel() {
      if (keepAliveTimer) {
        clearInterval(keepAliveTimer);
      }
      if (cleanup) {
        cleanup();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
    },
  });
}
